[package]
name = "main"
type = "bin"
authors = ["Sergey Potekhin"]
compiler_version = "0.17.0"

[dependencies]
noir_trie_proofs = { git = "https://github.com/aragonzkresearch/noir-trie-proofs", tag = "main", directory = "lib" }
